"""Builds every MUMU original synth track: WAV -> OGG + M4A, plus one generated chart module.

Usage:
    python tools/music/build_synth_tracks.py            # all tracks
    python tools/music/build_synth_tracks.py cloud-hop  # selected track ids

Everything is deterministic: fixed seeds, fixed scores, bit-exact encoder flags.
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from synth_core import HOLD_NOTE_MIN_BEATS, encode, write_wav  # noqa: E402
from synth_tracks import TRACKS, TrackResult  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
TMP = ROOT / "tmp" / "synth"
OUTPUT = ROOT / "public" / "assets" / "audio" / "v5" / "synth"
CHART_PATH = ROOT / "src" / "content" / "synthCharts.generated.ts"
MIN_NEW_TRACK_SECONDS = 45.0
MAX_DECODED_PEAK_DB = -0.1


def validate(result: TrackResult) -> dict[str, int]:
    chart = result.chart
    notes = chart["notes"]
    sections = chart["sections"]
    total_beats = chart["totalBeats"]
    name = result.id
    assert notes, f"{name}: no notes"
    assert sections[0]["startBeat"] == 0 and sections[-1]["endBeat"] == total_beats, f"{name}: sections must span the song"
    for previous, current in zip(sections, sections[1:]):
        assert previous["endBeat"] == current["startBeat"], f"{name}: section gap at {current['id']}"
    assert {section["mode"] for section in sections} == {"play", "listen"}, f"{name}: needs play and listen sections"
    lane_end = [-1e9] * 5
    last_beat = -1e9
    holds = 0
    for note in notes:
        beat, duration, lane = note["beat"], note["duration"], note["lane"]
        assert 0 <= lane <= 4, f"{name}: bad lane {note}"
        assert beat >= last_beat, f"{name}: notes out of order at {beat}"
        # Neon Run's V5 chart ends its last hold inside the audio tail; new tracks must end on the last beat.
        limit = result.seconds * chart["bpm"] / 60 if name == "neon-run" else total_beats
        assert 0 <= beat < total_beats and beat + duration <= limit + 1e-9, f"{name}: note outside song {note}"
        assert beat >= lane_end[lane] - 1e-9, f"{name}: lane {lane} overlap at beat {beat}"
        is_hold = duration >= HOLD_NOTE_MIN_BEATS
        holds += is_hold
        lane_end[lane] = beat + (duration if is_hold else 0.25)
        last_beat = beat
    if name != "neon-run":
        assert result.seconds >= MIN_NEW_TRACK_SECONDS, f"{name}: only {result.seconds:.1f}s"
        assert holds >= 4, f"{name}: needs hold notes"
        assert len({note["lane"] for note in notes}) == 5, f"{name}: must use all five lanes"
    return {"notes": len(notes), "holds": holds}


def write_chart(results: list[TrackResult]) -> None:
    payload = json.dumps({result.id: result.chart for result in results}, ensure_ascii=False, indent=2)
    CHART_PATH.write_text(
        "// Generated by tools/music/build_synth_tracks.py. Do not edit by hand.\n"
        'import type { GeneratedTrack } from "./fastCharts.generated";\n'
        f"export const synthTracks: Record<string, GeneratedTrack> = {payload};\n",
        encoding="utf-8",
    )


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()[:12]


def decoded_peak_db(path: Path) -> float:
    """Sample peak of the decoded file, so codec overshoot is caught before it reaches a classroom speaker."""
    probe = subprocess.run(
        ["ffmpeg", "-hide_banner", "-nostats", "-i", str(path), "-af", "volumedetect", "-f", "null", "-"],
        cwd=ROOT, check=True, capture_output=True, text=True, encoding="utf-8", errors="replace",
    )
    match = re.search(r"max_volume:\s*(-?[\d.]+) dB", probe.stderr)
    if not match:
        raise RuntimeError(f"Could not measure peak for {path}")
    return float(match.group(1))


def main(selected: list[str]) -> None:
    TMP.mkdir(parents=True, exist_ok=True)
    known = {builder.__name__.replace("_", "-") for builder in TRACKS}
    unknown = set(selected) - known
    if unknown:
        raise SystemExit(f"Unknown track id(s): {', '.join(sorted(unknown))}. Known: {', '.join(sorted(known))}")
    results: list[TrackResult] = []
    for builder in TRACKS:
        result = builder()
        stats = validate(result)
        results.append(result)
        track_id = builder.__name__.replace("_", "-")
        if selected and track_id not in selected:
            continue
        wav_path = TMP / f"{result.id}.wav"
        write_wav(result.audio, wav_path)
        outputs = encode(wav_path, OUTPUT, result.id, ROOT, loudness=result.loudness, limit=result.limit)
        peaks = {path.suffix[1:]: decoded_peak_db(path) for path in outputs}
        for kind, peak in peaks.items():
            if peak > MAX_DECODED_PEAK_DB:
                raise SystemExit(f"{result.id}.{kind}: decoded peak {peak:+.1f} dBFS would clip")
        print(
            f"{result.id:13s} {result.chart['bpm']:>3} BPM  {result.seconds:5.1f}s  "
            f"{stats['notes']:3d} notes ({stats['holds']} holds)  wav {digest(wav_path)}  "
            + "  ".join(f"{path.suffix[1:]} {digest(path)} peak {peaks[path.suffix[1:]]:+.1f}dB" for path in outputs)
        )
    # The chart module always contains every track so partial rebuilds never drop a song.
    write_chart(results)
    print(f"Wrote {CHART_PATH.relative_to(ROOT)} with {len(results)} tracks")


if __name__ == "__main__":
    main(sys.argv[1:])
