// Generated by tools/build_real_music.py. Do not edit by hand.
export interface GeneratedChartNote { beat: number; duration: number; midi: number; lane: number; accent: boolean; }
export interface GeneratedTrack { bpm: number; totalBeats: number; notes: GeneratedChartNote[]; sections: { id: string; label: string; startBeat: number; endBeat: number; mode: "play" | "listen"; }[]; }
export const producedTracks: Record<string, GeneratedTrack> = {
  "turkish-march": {
    "bpm": 129,
    "totalBeats": 150.952,
    "notes": [
      {
        "beat": 5.048,
        "duration": 1.833,
        "midi": 81,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 7.594,
        "duration": 1.402,
        "midi": 81,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 9.541,
        "duration": 1.078,
        "midi": 81,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 11.039,
        "duration": 0.755,
        "midi": 79,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 12.088,
        "duration": 0.827,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 13.236,
        "duration": 1.366,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 15.133,
        "duration": 1.438,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 17.13,
        "duration": 0.827,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 18.278,
        "duration": 1.114,
        "midi": 81,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 19.826,
        "duration": 0.791,
        "midi": 81,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 20.924,
        "duration": 2.085,
        "midi": 81,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 23.819,
        "duration": 1.402,
        "midi": 81,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 25.766,
        "duration": 0.791,
        "midi": 81,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 26.865,
        "duration": 0.755,
        "midi": 79,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 27.913,
        "duration": 1.15,
        "midi": 74,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 29.511,
        "duration": 0.755,
        "midi": 74,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 30.559,
        "duration": 1.006,
        "midi": 74,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 31.957,
        "duration": 0.791,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 33.055,
        "duration": 0.719,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 34.054,
        "duration": 0.755,
        "midi": 79,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 35.102,
        "duration": 2.157,
        "midi": 79,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 38.097,
        "duration": 0.755,
        "midi": 77,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 39.146,
        "duration": 1.797,
        "midi": 77,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 41.642,
        "duration": 0.755,
        "midi": 74,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 42.69,
        "duration": 1.042,
        "midi": 69,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 44.138,
        "duration": 0.971,
        "midi": 69,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 45.486,
        "duration": 1.258,
        "midi": 69,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 47.233,
        "duration": 0.719,
        "midi": 69,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 48.232,
        "duration": 0.755,
        "midi": 69,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 49.28,
        "duration": 0.863,
        "midi": 69,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 50.478,
        "duration": 0.827,
        "midi": 69,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 51.626,
        "duration": 0.791,
        "midi": 64,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 52.725,
        "duration": 0.719,
        "midi": 63,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 53.723,
        "duration": 1.078,
        "midi": 63,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 55.221,
        "duration": 0.719,
        "midi": 81,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 56.219,
        "duration": 0.755,
        "midi": 81,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 57.268,
        "duration": 0.755,
        "midi": 72,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 58.316,
        "duration": 0.719,
        "midi": 72,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 59.315,
        "duration": 1.869,
        "midi": 72,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 61.911,
        "duration": 0.755,
        "midi": 74,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 62.959,
        "duration": 0.971,
        "midi": 74,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 64.307,
        "duration": 1.186,
        "midi": 74,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 65.954,
        "duration": 0.791,
        "midi": 74,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 67.053,
        "duration": 1.042,
        "midi": 74,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 68.5,
        "duration": 0.719,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 69.499,
        "duration": 0.755,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 70.547,
        "duration": 1.438,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 72.544,
        "duration": 1.114,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 74.092,
        "duration": 0.791,
        "midi": 72,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 75.19,
        "duration": 1.042,
        "midi": 72,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 76.638,
        "duration": 0.791,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 77.736,
        "duration": 1.438,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 79.733,
        "duration": 1.474,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 81.78,
        "duration": 0.899,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 83.028,
        "duration": 1.15,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 84.625,
        "duration": 1.15,
        "midi": 63,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 86.223,
        "duration": 0.755,
        "midi": 63,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 87.271,
        "duration": 1.042,
        "midi": 64,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 88.719,
        "duration": 0.755,
        "midi": 64,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 89.768,
        "duration": 0.755,
        "midi": 64,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 90.816,
        "duration": 0.719,
        "midi": 72,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 91.814,
        "duration": 0.755,
        "midi": 72,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 92.863,
        "duration": 1.186,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 94.51,
        "duration": 1.474,
        "midi": 71,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 96.557,
        "duration": 1.438,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 98.554,
        "duration": 1.042,
        "midi": 69,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 100.002,
        "duration": 0.719,
        "midi": 69,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 101.0,
        "duration": 0.719,
        "midi": 69,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 101.999,
        "duration": 1.797,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 104.495,
        "duration": 1.438,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 106.492,
        "duration": 1.042,
        "midi": 68,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 107.939,
        "duration": 0.719,
        "midi": 68,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 108.938,
        "duration": 1.15,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 110.535,
        "duration": 1.402,
        "midi": 71,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 112.482,
        "duration": 1.761,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 114.929,
        "duration": 0.719,
        "midi": 69,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 115.927,
        "duration": 0.719,
        "midi": 69,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 116.926,
        "duration": 1.078,
        "midi": 69,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 118.423,
        "duration": 1.402,
        "midi": 71,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 120.37,
        "duration": 1.438,
        "midi": 71,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 122.367,
        "duration": 1.042,
        "midi": 68,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 123.815,
        "duration": 0.755,
        "midi": 68,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 124.863,
        "duration": 1.618,
        "midi": 81,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 127.11,
        "duration": 1.402,
        "midi": 81,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 129.057,
        "duration": 1.006,
        "midi": 78,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 130.455,
        "duration": 1.006,
        "midi": 78,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 131.853,
        "duration": 1.042,
        "midi": 78,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 133.3,
        "duration": 0.827,
        "midi": 61,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 134.449,
        "duration": 1.186,
        "midi": 61,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 136.096,
        "duration": 1.366,
        "midi": 61,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 137.993,
        "duration": 0.863,
        "midi": 61,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 139.191,
        "duration": 0.899,
        "midi": 73,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 140.439,
        "duration": 1.114,
        "midi": 73,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 141.987,
        "duration": 1.006,
        "midi": 73,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 143.385,
        "duration": 1.006,
        "midi": 61,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 144.783,
        "duration": 1.006,
        "midi": 61,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 146.18,
        "duration": 1.042,
        "midi": 61,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 147.628,
        "duration": 0.851,
        "midi": 81,
        "lane": 2,
        "accent": false
      }
    ],
    "sections": [
      {
        "id": "count-in",
        "label": "음악을 기다려요",
        "startBeat": 0,
        "endBeat": 4,
        "mode": "listen"
      },
      {
        "id": "theme-1",
        "label": "첫 번째 주제",
        "startBeat": 4,
        "endBeat": 47.0,
        "mode": "play"
      },
      {
        "id": "listen",
        "label": "피아노의 셈여림을 들어요",
        "startBeat": 47.0,
        "endBeat": 70.65,
        "mode": "listen"
      },
      {
        "id": "theme-2",
        "label": "달라진 주제",
        "startBeat": 70.65,
        "endBeat": 117.95,
        "mode": "play"
      },
      {
        "id": "finale",
        "label": "마지막 피날레",
        "startBeat": 117.95,
        "endBeat": 150.952,
        "mode": "play"
      }
    ]
  },
  "can-can": {
    "bpm": 185,
    "totalBeats": 233.246,
    "notes": [
      {
        "beat": 5.074,
        "duration": 1.598,
        "midi": 69,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 7.293,
        "duration": 1.701,
        "midi": 81,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 9.656,
        "duration": 1.237,
        "midi": 81,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 11.374,
        "duration": 1.186,
        "midi": 62,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 13.021,
        "duration": 1.134,
        "midi": 62,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 14.596,
        "duration": 1.134,
        "midi": 83,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 16.171,
        "duration": 1.546,
        "midi": 83,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 18.319,
        "duration": 1.186,
        "midi": 83,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 19.966,
        "duration": 1.804,
        "midi": 83,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 22.471,
        "duration": 1.495,
        "midi": 80,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 24.548,
        "duration": 1.495,
        "midi": 80,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 26.624,
        "duration": 1.495,
        "midi": 50,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 28.7,
        "duration": 1.134,
        "midi": 50,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 30.275,
        "duration": 1.083,
        "midi": 67,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 31.779,
        "duration": 1.443,
        "midi": 67,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 33.783,
        "duration": 1.907,
        "midi": 67,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 36.432,
        "duration": 1.134,
        "midi": 67,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 38.008,
        "duration": 1.443,
        "midi": 57,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 40.012,
        "duration": 1.083,
        "midi": 50,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 41.516,
        "duration": 1.083,
        "midi": 50,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 43.019,
        "duration": 1.598,
        "midi": 78,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 45.239,
        "duration": 2.371,
        "midi": 78,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 48.532,
        "duration": 1.083,
        "midi": 62,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 50.035,
        "duration": 1.031,
        "midi": 62,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 51.467,
        "duration": 1.598,
        "midi": 83,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 53.687,
        "duration": 2.371,
        "midi": 83,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 56.98,
        "duration": 1.031,
        "midi": 83,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 58.412,
        "duration": 1.083,
        "midi": 83,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 59.916,
        "duration": 1.598,
        "midi": 83,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 62.135,
        "duration": 2.01,
        "midi": 83,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 64.927,
        "duration": 1.083,
        "midi": 83,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 66.431,
        "duration": 1.34,
        "midi": 90,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 68.292,
        "duration": 1.65,
        "midi": 90,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 70.583,
        "duration": 3.041,
        "midi": 78,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 74.807,
        "duration": 1.598,
        "midi": 69,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 77.027,
        "duration": 2.99,
        "midi": 69,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 81.179,
        "duration": 1.546,
        "midi": 69,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 83.327,
        "duration": 1.289,
        "midi": 74,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 85.117,
        "duration": 1.495,
        "midi": 74,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 87.193,
        "duration": 1.65,
        "midi": 74,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 89.484,
        "duration": 1.546,
        "midi": 74,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 91.632,
        "duration": 1.907,
        "midi": 74,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 94.281,
        "duration": 1.083,
        "midi": 69,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 95.785,
        "duration": 1.804,
        "midi": 62,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 98.29,
        "duration": 1.083,
        "midi": 50,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 99.794,
        "duration": 1.495,
        "midi": 50,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 101.87,
        "duration": 0.979,
        "midi": 69,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 103.23,
        "duration": 1.083,
        "midi": 69,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 104.734,
        "duration": 1.031,
        "midi": 69,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 106.166,
        "duration": 1.083,
        "midi": 79,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 107.669,
        "duration": 1.083,
        "midi": 79,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 109.173,
        "duration": 1.443,
        "midi": 62,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 111.178,
        "duration": 1.186,
        "midi": 62,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 112.824,
        "duration": 1.031,
        "midi": 62,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 114.256,
        "duration": 1.083,
        "midi": 62,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 115.76,
        "duration": 2.217,
        "midi": 71,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 118.838,
        "duration": 0.979,
        "midi": 71,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 120.198,
        "duration": 1.031,
        "midi": 71,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 121.63,
        "duration": 1.546,
        "midi": 71,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 123.778,
        "duration": 1.546,
        "midi": 67,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 125.926,
        "duration": 0.979,
        "midi": 67,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 127.286,
        "duration": 1.134,
        "midi": 67,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 128.861,
        "duration": 1.083,
        "midi": 43,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 130.365,
        "duration": 1.031,
        "midi": 43,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 131.797,
        "duration": 1.134,
        "midi": 69,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 133.372,
        "duration": 1.031,
        "midi": 69,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 134.804,
        "duration": 1.031,
        "midi": 69,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 136.236,
        "duration": 1.392,
        "midi": 71,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 138.169,
        "duration": 1.031,
        "midi": 71,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 139.601,
        "duration": 1.083,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 141.104,
        "duration": 1.134,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 142.679,
        "duration": 1.443,
        "midi": 69,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 144.684,
        "duration": 1.031,
        "midi": 69,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 146.116,
        "duration": 1.083,
        "midi": 62,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 147.619,
        "duration": 1.495,
        "midi": 62,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 149.696,
        "duration": 0.979,
        "midi": 62,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 151.056,
        "duration": 1.392,
        "midi": 62,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 152.989,
        "duration": 0.979,
        "midi": 62,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 154.349,
        "duration": 1.65,
        "midi": 62,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 156.64,
        "duration": 1.392,
        "midi": 64,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 158.573,
        "duration": 1.289,
        "midi": 67,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 160.363,
        "duration": 1.443,
        "midi": 67,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 162.368,
        "duration": 1.804,
        "midi": 81,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 164.874,
        "duration": 1.701,
        "midi": 81,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 167.236,
        "duration": 1.392,
        "midi": 62,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 169.169,
        "duration": 1.392,
        "midi": 61,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 171.102,
        "duration": 1.392,
        "midi": 61,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 173.035,
        "duration": 1.392,
        "midi": 61,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 174.969,
        "duration": 1.34,
        "midi": 50,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 176.83,
        "duration": 1.392,
        "midi": 50,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 178.763,
        "duration": 1.443,
        "midi": 45,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 180.768,
        "duration": 1.443,
        "midi": 45,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 182.772,
        "duration": 2.887,
        "midi": 45,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 186.782,
        "duration": 1.392,
        "midi": 45,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 188.715,
        "duration": 2.887,
        "midi": 57,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 192.724,
        "duration": 1.443,
        "midi": 57,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 194.729,
        "duration": 1.443,
        "midi": 57,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 196.733,
        "duration": 2.938,
        "midi": 57,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 200.814,
        "duration": 1.392,
        "midi": 51,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 202.747,
        "duration": 1.443,
        "midi": 51,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 204.752,
        "duration": 1.34,
        "midi": 62,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 206.613,
        "duration": 1.443,
        "midi": 62,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 208.618,
        "duration": 0.979,
        "midi": 45,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 209.978,
        "duration": 1.031,
        "midi": 45,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 211.41,
        "duration": 2.062,
        "midi": 45,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 214.274,
        "duration": 1.495,
        "midi": 45,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 216.35,
        "duration": 1.289,
        "midi": 69,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 218.14,
        "duration": 1.443,
        "midi": 69,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 220.145,
        "duration": 0.979,
        "midi": 69,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 221.505,
        "duration": 1.134,
        "midi": 69,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 223.08,
        "duration": 1.031,
        "midi": 69,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 224.512,
        "duration": 1.289,
        "midi": 69,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 226.302,
        "duration": 1.031,
        "midi": 69,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 227.734,
        "duration": 1.221,
        "midi": 62,
        "lane": 2,
        "accent": false
      }
    ],
    "sections": [
      {
        "id": "count-in",
        "label": "음악을 기다려요",
        "startBeat": 0,
        "endBeat": 4,
        "mode": "listen"
      },
      {
        "id": "theme-1",
        "label": "첫 번째 주제",
        "startBeat": 4,
        "endBeat": 65.667,
        "mode": "play"
      },
      {
        "id": "listen",
        "label": "관현악의 층이 커지는 순간을 들어요",
        "startBeat": 65.667,
        "endBeat": 99.583,
        "mode": "listen"
      },
      {
        "id": "theme-2",
        "label": "달라진 주제",
        "startBeat": 99.583,
        "endBeat": 167.417,
        "mode": "play"
      },
      {
        "id": "finale",
        "label": "마지막 피날레",
        "startBeat": 167.417,
        "endBeat": 233.246,
        "mode": "play"
      }
    ]
  },
  "william-tell": {
    "bpm": 152,
    "totalBeats": 192.353,
    "notes": [
      {
        "beat": 4.941,
        "duration": 1.398,
        "midi": 71,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 6.882,
        "duration": 1.016,
        "midi": 71,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 8.294,
        "duration": 1.609,
        "midi": 64,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 10.529,
        "duration": 1.694,
        "midi": 64,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 12.882,
        "duration": 1.016,
        "midi": 64,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 14.294,
        "duration": 1.398,
        "midi": 64,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 16.235,
        "duration": 1.398,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 18.177,
        "duration": 1.355,
        "midi": 68,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 20.059,
        "duration": 1.398,
        "midi": 68,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 22.0,
        "duration": 1.821,
        "midi": 68,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 24.53,
        "duration": 1.059,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 26.0,
        "duration": 2.118,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 28.941,
        "duration": 1.059,
        "midi": 67,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 30.412,
        "duration": 2.913,
        "midi": 78,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 37.883,
        "duration": 0.932,
        "midi": 78,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 39.177,
        "duration": 1.567,
        "midi": 78,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 41.353,
        "duration": 1.059,
        "midi": 78,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 42.824,
        "duration": 1.398,
        "midi": 78,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 44.765,
        "duration": 1.44,
        "midi": 71,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 46.765,
        "duration": 1.44,
        "midi": 71,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 48.765,
        "duration": 0.889,
        "midi": 68,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 50.0,
        "duration": 0.889,
        "midi": 68,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 51.236,
        "duration": 1.779,
        "midi": 68,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 53.706,
        "duration": 1.44,
        "midi": 64,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 55.706,
        "duration": 1.016,
        "midi": 64,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 57.118,
        "duration": 1.101,
        "midi": 64,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 58.647,
        "duration": 1.44,
        "midi": 64,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 60.647,
        "duration": 1.44,
        "midi": 64,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 62.647,
        "duration": 1.44,
        "midi": 64,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 64.647,
        "duration": 1.482,
        "midi": 71,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 66.706,
        "duration": 0.847,
        "midi": 71,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 67.883,
        "duration": 0.932,
        "midi": 78,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 69.177,
        "duration": 1.101,
        "midi": 78,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 70.706,
        "duration": 2.499,
        "midi": 78,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 74.177,
        "duration": 1.44,
        "midi": 85,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 76.177,
        "duration": 1.144,
        "midi": 85,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 77.765,
        "duration": 1.101,
        "midi": 64,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 79.295,
        "duration": 1.398,
        "midi": 64,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 81.236,
        "duration": 1.44,
        "midi": 66,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 83.236,
        "duration": 1.101,
        "midi": 66,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 84.765,
        "duration": 0.805,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 85.883,
        "duration": 1.44,
        "midi": 66,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 87.883,
        "duration": 1.059,
        "midi": 64,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 89.353,
        "duration": 1.44,
        "midi": 64,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 91.353,
        "duration": 1.101,
        "midi": 66,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 92.883,
        "duration": 2.245,
        "midi": 66,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 96.001,
        "duration": 0.974,
        "midi": 88,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 97.354,
        "duration": 1.44,
        "midi": 88,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 99.354,
        "duration": 1.906,
        "midi": 66,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 102.001,
        "duration": 1.44,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 104.001,
        "duration": 1.864,
        "midi": 68,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 106.589,
        "duration": 1.059,
        "midi": 68,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 108.059,
        "duration": 1.101,
        "midi": 68,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 109.589,
        "duration": 1.101,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 111.118,
        "duration": 1.44,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 113.118,
        "duration": 1.44,
        "midi": 71,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 115.118,
        "duration": 1.101,
        "midi": 71,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 116.648,
        "duration": 1.906,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 119.295,
        "duration": 1.398,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 121.236,
        "duration": 1.482,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 123.295,
        "duration": 1.779,
        "midi": 71,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 125.765,
        "duration": 1.101,
        "midi": 71,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 127.295,
        "duration": 1.398,
        "midi": 71,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 129.236,
        "duration": 1.821,
        "midi": 71,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 131.765,
        "duration": 1.821,
        "midi": 71,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 134.295,
        "duration": 1.44,
        "midi": 64,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 136.295,
        "duration": 1.44,
        "midi": 64,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 138.295,
        "duration": 1.44,
        "midi": 64,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 140.295,
        "duration": 1.059,
        "midi": 64,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 141.766,
        "duration": 1.101,
        "midi": 64,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 143.295,
        "duration": 1.44,
        "midi": 64,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 145.295,
        "duration": 2.329,
        "midi": 66,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 148.53,
        "duration": 0.889,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 149.766,
        "duration": 1.186,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 151.413,
        "duration": 1.059,
        "midi": 68,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 152.883,
        "duration": 1.567,
        "midi": 76,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 155.06,
        "duration": 1.101,
        "midi": 76,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 156.589,
        "duration": 1.101,
        "midi": 68,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 158.119,
        "duration": 1.482,
        "midi": 68,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 160.177,
        "duration": 2.202,
        "midi": 66,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 163.236,
        "duration": 1.482,
        "midi": 66,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 165.295,
        "duration": 0.974,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 166.648,
        "duration": 0.932,
        "midi": 76,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 167.942,
        "duration": 1.059,
        "midi": 76,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 169.413,
        "duration": 1.906,
        "midi": 76,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 172.06,
        "duration": 1.101,
        "midi": 72,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 173.589,
        "duration": 2.245,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 176.707,
        "duration": 2.202,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 179.766,
        "duration": 1.482,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 181.825,
        "duration": 0.847,
        "midi": 66,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 183.001,
        "duration": 1.482,
        "midi": 66,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 185.06,
        "duration": 1.864,
        "midi": 42,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 187.648,
        "duration": 1.003,
        "midi": 37,
        "lane": 0,
        "accent": false
      }
    ],
    "sections": [
      {
        "id": "count-in",
        "label": "음악을 기다려요",
        "startBeat": 0,
        "endBeat": 4,
        "mode": "listen"
      },
      {
        "id": "theme-1",
        "label": "첫 번째 주제",
        "startBeat": 4,
        "endBeat": 54.667,
        "mode": "play"
      },
      {
        "id": "listen",
        "label": "금관과 타악기의 대화를 들어요",
        "startBeat": 54.667,
        "endBeat": 82.533,
        "mode": "listen"
      },
      {
        "id": "theme-2",
        "label": "달라진 주제",
        "startBeat": 82.533,
        "endBeat": 138.267,
        "mode": "play"
      },
      {
        "id": "finale",
        "label": "마지막 피날레",
        "startBeat": 138.267,
        "endBeat": 192.353,
        "mode": "play"
      }
    ]
  },
  "hungarian-dance": {
    "bpm": 162,
    "totalBeats": 204.745,
    "notes": [
      {
        "beat": 4.94,
        "duration": 1.174,
        "midi": 49,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 6.57,
        "duration": 1.535,
        "midi": 69,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 8.702,
        "duration": 1.896,
        "midi": 69,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 11.335,
        "duration": 1.896,
        "midi": 62,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 13.968,
        "duration": 1.49,
        "midi": 62,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 16.037,
        "duration": 1.083,
        "midi": 62,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 17.542,
        "duration": 1.896,
        "midi": 62,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 20.175,
        "duration": 1.535,
        "midi": 73,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 22.307,
        "duration": 1.535,
        "midi": 73,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 24.438,
        "duration": 1.49,
        "midi": 80,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 26.507,
        "duration": 1.535,
        "midi": 80,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 28.639,
        "duration": 1.625,
        "midi": 80,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 30.896,
        "duration": 1.038,
        "midi": 76,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 32.338,
        "duration": 1.67,
        "midi": 76,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 34.657,
        "duration": 2.212,
        "midi": 76,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 37.729,
        "duration": 1.625,
        "midi": 76,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 39.986,
        "duration": 1.806,
        "midi": 76,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 42.494,
        "duration": 1.083,
        "midi": 76,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 43.999,
        "duration": 1.309,
        "midi": 76,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 45.817,
        "duration": 1.219,
        "midi": 77,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 47.51,
        "duration": 1.941,
        "midi": 77,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 50.205,
        "duration": 1.219,
        "midi": 77,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 51.898,
        "duration": 1.76,
        "midi": 77,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 54.343,
        "duration": 1.58,
        "midi": 77,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 56.537,
        "duration": 1.49,
        "midi": 77,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 58.606,
        "duration": 1.354,
        "midi": 77,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 60.487,
        "duration": 1.76,
        "midi": 78,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 62.932,
        "duration": 1.174,
        "midi": 78,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 64.562,
        "duration": 1.986,
        "midi": 57,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 67.321,
        "duration": 0.903,
        "midi": 57,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 68.575,
        "duration": 1.219,
        "midi": 59,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 70.267,
        "duration": 1.58,
        "midi": 59,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 72.462,
        "duration": 1.67,
        "midi": 78,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 74.781,
        "duration": 0.903,
        "midi": 78,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 76.035,
        "duration": 1.083,
        "midi": 78,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 77.54,
        "duration": 0.903,
        "midi": 76,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 78.794,
        "duration": 1.896,
        "midi": 76,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 81.427,
        "duration": 1.896,
        "midi": 76,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 84.06,
        "duration": 1.354,
        "midi": 83,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 85.941,
        "duration": 1.444,
        "midi": 83,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 87.947,
        "duration": 1.038,
        "midi": 83,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 89.389,
        "duration": 1.174,
        "midi": 83,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 91.019,
        "duration": 1.219,
        "midi": 80,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 92.712,
        "duration": 1.083,
        "midi": 80,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 94.216,
        "duration": 1.083,
        "midi": 80,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 95.721,
        "duration": 1.309,
        "midi": 80,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 97.539,
        "duration": 1.444,
        "midi": 80,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 99.545,
        "duration": 1.806,
        "midi": 81,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 102.053,
        "duration": 1.128,
        "midi": 81,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 103.621,
        "duration": 1.083,
        "midi": 80,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 105.125,
        "duration": 1.309,
        "midi": 69,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 106.943,
        "duration": 1.58,
        "midi": 69,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 109.138,
        "duration": 3.105,
        "midi": 69,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 113.714,
        "duration": 1.941,
        "midi": 61,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 116.41,
        "duration": 1.715,
        "midi": 61,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 118.792,
        "duration": 2.392,
        "midi": 78,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 122.115,
        "duration": 1.49,
        "midi": 78,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 124.184,
        "duration": 1.806,
        "midi": 78,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 126.692,
        "duration": 1.851,
        "midi": 85,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 129.262,
        "duration": 1.309,
        "midi": 85,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 131.08,
        "duration": 1.49,
        "midi": 85,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 133.149,
        "duration": 1.038,
        "midi": 85,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 134.591,
        "duration": 1.535,
        "midi": 83,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 136.723,
        "duration": 1.083,
        "midi": 83,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 138.228,
        "duration": 1.038,
        "midi": 83,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 139.67,
        "duration": 1.083,
        "midi": 80,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 141.174,
        "duration": 1.444,
        "midi": 80,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 143.18,
        "duration": 1.264,
        "midi": 80,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 144.936,
        "duration": 0.903,
        "midi": 81,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 146.19,
        "duration": 1.399,
        "midi": 81,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 148.133,
        "duration": 0.948,
        "midi": 80,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 149.45,
        "duration": 1.444,
        "midi": 69,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 151.456,
        "duration": 1.083,
        "midi": 69,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 152.961,
        "duration": 1.219,
        "midi": 77,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 154.653,
        "duration": 0.993,
        "midi": 77,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 156.033,
        "duration": 1.76,
        "midi": 77,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 158.478,
        "duration": 1.986,
        "midi": 61,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 161.236,
        "duration": 1.038,
        "midi": 61,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 162.678,
        "duration": 1.219,
        "midi": 77,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 164.371,
        "duration": 1.174,
        "midi": 78,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 166.001,
        "duration": 1.715,
        "midi": 78,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 168.383,
        "duration": 1.67,
        "midi": 78,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 170.703,
        "duration": 0.948,
        "midi": 70,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 172.02,
        "duration": 2.799,
        "midi": 70,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 175.907,
        "duration": 1.444,
        "midi": 68,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 177.913,
        "duration": 2.483,
        "midi": 68,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 181.361,
        "duration": 1.083,
        "midi": 70,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 182.866,
        "duration": 1.625,
        "midi": 70,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 185.123,
        "duration": 0.903,
        "midi": 70,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 186.376,
        "duration": 1.219,
        "midi": 70,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 188.069,
        "duration": 3.105,
        "midi": 70,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 193.336,
        "duration": 1.069,
        "midi": 71,
        "lane": 1,
        "accent": false
      }
    ],
    "sections": [
      {
        "id": "count-in",
        "label": "음악을 기다려요",
        "startBeat": 0,
        "endBeat": 4,
        "mode": "listen"
      },
      {
        "id": "theme-1",
        "label": "첫 번째 주제",
        "startBeat": 4,
        "endBeat": 58.0,
        "mode": "play"
      },
      {
        "id": "listen",
        "label": "느려졌다 빨라지는 숨을 들어요",
        "startBeat": 58.0,
        "endBeat": 87.7,
        "mode": "listen"
      },
      {
        "id": "theme-2",
        "label": "달라진 주제",
        "startBeat": 87.7,
        "endBeat": 147.1,
        "mode": "play"
      },
      {
        "id": "finale",
        "label": "마지막 피날레",
        "startBeat": 147.1,
        "endBeat": 204.745,
        "mode": "play"
      }
    ]
  }
};
