// Generated by tools/music/build_synth_tracks.py. Do not edit by hand.
import type { GeneratedTrack } from "./fastCharts.generated";
export const synthTracks: Record<string, GeneratedTrack> = {
  "neon-run": {
    "bpm": 150,
    "totalBeats": 196,
    "notes": [
      {
        "beat": 4.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 5.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 6.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 7.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 8.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 9.0,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 10.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 11.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 12.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 13.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 14.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 15.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 16.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 17.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 18.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 19.0,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 20.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 20.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 21.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 21.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 22.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 22.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 23.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 23.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 24.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 24.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 25.0,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 25.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 26.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 26.5,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 27.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 27.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 28.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 28.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 29.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 29.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 30.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 30.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 31.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 31.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 32.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 32.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 33.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 33.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 34.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 34.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 35.0,
        "duration": 1.8,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 35.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 36.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 36.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 37.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 37.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 38.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 38.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 39.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 39.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 40.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 40.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 41.0,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 41.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 42.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 42.5,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 43.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 43.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 44.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 44.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 45.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 45.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 46.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 46.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 47.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 47.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 48.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 48.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 49.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 49.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 50.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 50.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 51.0,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 51.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 52.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 52.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 53.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 53.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 54.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 54.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 55.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 55.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 56.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 56.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 57.0,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 57.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 58.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 58.5,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 59.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 59.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 60.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 60.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 61.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 61.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 62.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 62.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 63.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 63.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 64.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 64.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 65.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 65.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 66.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 66.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 67.0,
        "duration": 1.8,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 67.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 68,
        "duration": 2.5,
        "midi": 55,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 71,
        "duration": 0.65,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 72,
        "duration": 2.5,
        "midi": 67,
        "lane": 3,
        "accent": true
      },
      {
        "beat": 75,
        "duration": 0.65,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 76,
        "duration": 2.5,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 79,
        "duration": 0.65,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 80,
        "duration": 2.5,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 83,
        "duration": 0.65,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 84.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 84.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 85.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 85.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 86.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 86.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 87.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 87.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 88.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 88.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 89.0,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 89.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 90.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 90.5,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 91.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 91.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 92.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 92.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 93.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 93.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 94.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 94.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 95.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 95.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 96.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 96.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 97.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 97.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 98.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 98.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 99.0,
        "duration": 1.8,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 99.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 100.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 100.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 101.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 101.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 102.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 102.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 103.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 103.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 104.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 104.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 105.0,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 105.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 106.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 106.5,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 107.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 107.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 108.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 108.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 109.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 109.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 110.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 110.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 111.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 111.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 112.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 112.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 113.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 113.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 114.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 114.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 115.0,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 115.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 116.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 116.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 117.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 117.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 118.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 118.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 119.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 119.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 120.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 120.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 121.0,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 121.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 122.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 122.5,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 123.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 123.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 124.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 124.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 125.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 125.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 126.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 126.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 127.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 127.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 128.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 128.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 129.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 129.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 130.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 130.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 131.0,
        "duration": 1.8,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 131.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 132.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 132.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 133.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 133.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 134.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 134.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 135.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 135.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 136.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 136.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 137.0,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 137.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 138.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 138.5,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 139.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 139.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 140.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 140.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 141.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 141.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 142.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 142.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 143.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 143.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 144.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 144.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 145.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 145.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 146.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 146.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 147.0,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 147.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 148.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 148.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 149.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 149.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 150.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 150.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 151.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 151.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 152.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 152.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 153.0,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 153.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 154.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 154.5,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 155.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 155.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 156.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 156.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 157.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 157.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 158.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 158.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 159.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 159.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 160.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 160.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 161.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 161.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 162.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 162.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 163.0,
        "duration": 1.8,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 163.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 164.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 164.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 165.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 165.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 166.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 166.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 167.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 167.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 168.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 168.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 169.0,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 169.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 170.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 170.5,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 171.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 171.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 172.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 172.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 173.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 173.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 174.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 174.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 175.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 175.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 176.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 176.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 177.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 177.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 178.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 178.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 179.0,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 179.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 180.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 180.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 181.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 181.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 182.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 182.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 183.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 183.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 184.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": true
      },
      {
        "beat": 184.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 185.0,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 185.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 186.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 186.5,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": false
      },
      {
        "beat": 187.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 187.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 188.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 188.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 189.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 189.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 190.0,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": true
      },
      {
        "beat": 190.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 191.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 191.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 192.0,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": true
      },
      {
        "beat": 192.5,
        "duration": 0.42,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 193.0,
        "duration": 0.42,
        "midi": 72,
        "lane": 4,
        "accent": false
      },
      {
        "beat": 193.5,
        "duration": 0.42,
        "midi": 60,
        "lane": 2,
        "accent": false
      },
      {
        "beat": 194.0,
        "duration": 0.42,
        "midi": 48,
        "lane": 0,
        "accent": true
      },
      {
        "beat": 194.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      },
      {
        "beat": 195.0,
        "duration": 1.8,
        "midi": 67,
        "lane": 3,
        "accent": false
      },
      {
        "beat": 195.5,
        "duration": 0.42,
        "midi": 55,
        "lane": 1,
        "accent": false
      }
    ],
    "sections": [
      {
        "id": "count-in",
        "label": "빛의 문이 열려요",
        "startBeat": 0,
        "endBeat": 4,
        "mode": "listen"
      },
      {
        "id": "launch",
        "label": "첫 번째 네온 주제",
        "startBeat": 4,
        "endBeat": 68,
        "mode": "play"
      },
      {
        "id": "break",
        "label": "신스의 층을 들어요",
        "startBeat": 68,
        "endBeat": 84,
        "mode": "listen"
      },
      {
        "id": "drive",
        "label": "더 빨라진 변주",
        "startBeat": 84,
        "endBeat": 148,
        "mode": "play"
      },
      {
        "id": "finale",
        "label": "별빛 피날레",
        "startBeat": 148,
        "endBeat": 196,
        "mode": "play"
      }
    ]
  }
};
